// Generated by CoffeeScript 1.7.1
(function() {
  define(['$', 'ko'], function($, ko) {
    var DynamicContent;
    DynamicContent = (function() {
      function DynamicContent() {
        $(document).on('click', '.click-test', function() {
          return alert('click event');
        });
      }

      return DynamicContent;

    })();
    return new DynamicContent();
  });

}).call(this);
