// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery', 'knockout'], function($, ko) {
    var Index;
    Index = (function() {
      function Index() {
        $(document).on('click', '.click-test', function() {
          return alert('click event');
        });
      }

      return Index;

    })();
    return new Index();
  });

}).call(this);
