// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    var Level2;
    Level2 = (function() {
      function Level2() {}

      return Level2;

    })();
    return new Level2();
  });

}).call(this);
